### ISSUE TITLE
Store time in ISO8601 instead of Epoch

### ISSUE THREAD

**Issue by teppah** [sunny-zuo/sir-goose-bot#1]
If the `time` field in [se25.json](https://github.com/sunny-zuo/sir-goose-bot/blob/master/data/se25.json) is in ISO8601, events would be much more user-editable and would allow for cleaner date manipulation logic with Luxon in [upcoming.js](https://github.com/sunny-zuo/sir-goose-bot/blob/master/commands/upcoming.js).

**Comment by sunny-zuo** [comment]
Tasks are now stored as MongoDB documents with `time` fields being a MongoDB Date type. Closing as this no longer applies.
