### ISSUE TITLE
Birthday Feature 🚀 🎂 🥳 🎉 

### ISSUE THREAD

**Issue by OrenLeung** [sunny-zuo/sir-goose-bot#9]
## Feature Request 
- [ ] store user's birthday in existing MongoDB database
- [ ] on the day of their birthday, it sends a message

## Implementation
- [ ] database to store the birthdays
- [ ] CRON job to check at the list of birthdays from the database certain time of the day

**Comment by sunny-zuo** [comment]
Thanks for the feature request! Unfortunately, I consider this feature to be outside the scope of my project which is now primarily focused on verification. Thus, I have closed the issue.
